// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/vm.proto

package vm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ProxmoxVmid   int32                  `protobuf:"varint,3,opt,name=proxmox_vmid,json=proxmoxVmid,proto3" json:"proxmox_vmid,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	NodeName      string                 `protobuf:"bytes,6,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VM) Reset() {
	*x = VM{}
	mi := &file_proto_vm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VM) ProtoMessage() {}

func (x *VM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VM.ProtoReflect.Descriptor instead.
func (*VM) Descriptor() ([]byte, []int) {
	return file_proto_vm_proto_rawDescGZIP(), []int{0}
}

func (x *VM) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VM) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *VM) GetProxmoxVmid() int32 {
	if x != nil {
		return x.ProxmoxVmid
	}
	return 0
}

func (x *VM) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VM) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VM) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type ListVMsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsRequest) Reset() {
	*x = ListVMsRequest{}
	mi := &file_proto_vm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsRequest) ProtoMessage() {}

func (x *ListVMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsRequest.ProtoReflect.Descriptor instead.
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return file_proto_vm_proto_rawDescGZIP(), []int{1}
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VM                  `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_proto_vm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_proto_vm_proto_rawDescGZIP(), []int{2}
}

func (x *ListVMsResponse) GetVms() []*VM {
	if x != nil {
		return x.Vms
	}
	return nil
}

type VMActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          int32                  `protobuf:"varint,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMActionRequest) Reset() {
	*x = VMActionRequest{}
	mi := &file_proto_vm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMActionRequest) ProtoMessage() {}

func (x *VMActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMActionRequest.ProtoReflect.Descriptor instead.
func (*VMActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_vm_proto_rawDescGZIP(), []int{3}
}

func (x *VMActionRequest) GetVmId() int32 {
	if x != nil {
		return x.VmId
	}
	return 0
}

type VMActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TaskUpid      string                 `protobuf:"bytes,3,opt,name=task_upid,json=taskUpid,proto3" json:"task_upid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMActionResponse) Reset() {
	*x = VMActionResponse{}
	mi := &file_proto_vm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMActionResponse) ProtoMessage() {}

func (x *VMActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMActionResponse.ProtoReflect.Descriptor instead.
func (*VMActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_vm_proto_rawDescGZIP(), []int{4}
}

func (x *VMActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VMActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VMActionResponse) GetTaskUpid() string {
	if x != nil {
		return x.TaskUpid
	}
	return ""
}

var File_proto_vm_proto protoreflect.FileDescriptor

const file_proto_vm_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/vm.proto\x12\x02vm\"\x99\x01\n" +
	"\x02VM\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\x12!\n" +
	"\fproxmox_vmid\x18\x03 \x01(\x05R\vproxmoxVmid\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tnode_name\x18\x06 \x01(\tR\bnodeName\"\x10\n" +
	"\x0eListVMsRequest\"+\n" +
	"\x0fListVMsResponse\x12\x18\n" +
	"\x03vms\x18\x01 \x03(\v2\x06.vm.VMR\x03vms\"&\n" +
	"\x0fVMActionRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\x05R\x04vmId\"c\n" +
	"\x10VMActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\ttask_upid\x18\x03 \x01(\tR\btaskUpid2\xe3\x01\n" +
	"\tVMService\x122\n" +
	"\aListVMs\x12\x12.vm.ListVMsRequest\x1a\x13.vm.ListVMsResponse\x124\n" +
	"\aStartVM\x12\x13.vm.VMActionRequest\x1a\x14.vm.VMActionResponse\x123\n" +
	"\x06StopVM\x12\x13.vm.VMActionRequest\x1a\x14.vm.VMActionResponse\x127\n" +
	"\n" +
	"ShutdownVM\x12\x13.vm.VMActionRequest\x1a\x14.vm.VMActionResponseB\x17Z\x15main-service/proto;vmb\x06proto3"

var (
	file_proto_vm_proto_rawDescOnce sync.Once
	file_proto_vm_proto_rawDescData []byte
)

func file_proto_vm_proto_rawDescGZIP() []byte {
	file_proto_vm_proto_rawDescOnce.Do(func() {
		file_proto_vm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vm_proto_rawDesc), len(file_proto_vm_proto_rawDesc)))
	})
	return file_proto_vm_proto_rawDescData
}

var file_proto_vm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_vm_proto_goTypes = []any{
	(*VM)(nil),               // 0: vm.VM
	(*ListVMsRequest)(nil),   // 1: vm.ListVMsRequest
	(*ListVMsResponse)(nil),  // 2: vm.ListVMsResponse
	(*VMActionRequest)(nil),  // 3: vm.VMActionRequest
	(*VMActionResponse)(nil), // 4: vm.VMActionResponse
}
var file_proto_vm_proto_depIdxs = []int32{
	0, // 0: vm.ListVMsResponse.vms:type_name -> vm.VM
	1, // 1: vm.VMService.ListVMs:input_type -> vm.ListVMsRequest
	3, // 2: vm.VMService.StartVM:input_type -> vm.VMActionRequest
	3, // 3: vm.VMService.StopVM:input_type -> vm.VMActionRequest
	3, // 4: vm.VMService.ShutdownVM:input_type -> vm.VMActionRequest
	2, // 5: vm.VMService.ListVMs:output_type -> vm.ListVMsResponse
	4, // 6: vm.VMService.StartVM:output_type -> vm.VMActionResponse
	4, // 7: vm.VMService.StopVM:output_type -> vm.VMActionResponse
	4, // 8: vm.VMService.ShutdownVM:output_type -> vm.VMActionResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_vm_proto_init() }
func file_proto_vm_proto_init() {
	if File_proto_vm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vm_proto_rawDesc), len(file_proto_vm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vm_proto_goTypes,
		DependencyIndexes: file_proto_vm_proto_depIdxs,
		MessageInfos:      file_proto_vm_proto_msgTypes,
	}.Build()
	File_proto_vm_proto = out.File
	file_proto_vm_proto_goTypes = nil
	file_proto_vm_proto_depIdxs = nil
}
